### ISSUE TITLE
The same metric name `complete-latency` was registered twice.

### ISSUE THREAD

**Issue by Junyulu** [ADSC-Cloud/resa-drs#2]
I have submitted "ResaSimExpServWCLoop.java " topology , but it didn't  work and throws some exceptions about metric register.Did you ever meet the problem  like that?And how can I solve it?
<img width="1438" alt="2016-12-19 7 13 42" src="https://cloud.githubusercontent.com/assets/24650990/21311105/7544ab08-c620-11e6-81e1-e0b2ee411039.png">
And this is part of the storm's configuration.
<img width="665" alt="2016-12-19 7 33 26" src="https://cloud.githubusercontent.com/assets/24650990/21311430/2347d080-c622-11e6-942c-480f69fde90a.png">

**Comment by fuzhengjia** [comment]
Thanks for the report, we will take a look at this

**Comment by fuzhengjia** [comment]
Hi Junyulu,

The reason for this issue is because of the ambiguation of the user manual and description on how to use Resa-drs. In fact, Resa-drs can work in two modes: a) the implicit mode; and b) the explicit mode. 

- In mode a), Resa-drs is independent and transparent to the application and developers (in your example, it should be SimExpServWCLoop.java without prefix "Resa"). We assume that the application developers are not aware of the existence of Resa-drs, i.e., the application is just a normal Storm topology. Only after the normal storm topology is submitted, will Resa-drs add its functionalities to the submitted one automatically.    

- In mode b), Resa-drs is binding with application development (ResaSimExpServWCLoop.java), meaning the Resa-drs related functionalities must be explicitly and manually added by the developers to the topology before it is compiled and submitted (therefore, must include Resa-drs dependency jars).  For example, in ResaSimExpServWCLoop.java `TopologyBuilder builder = new ResaTopologyBuilder();`, which explicitly adds Resa-drs support including those metric registration. 

Suggested solution: 

   1. If you just want to use Resa-drs as a tool and scheduing module, you can run SimExpServWCLoop.java instead of ResaSimExpServWCLoop.java; 
   2. Or if you want  to try ResaSimExpServWCLoop.java for the explicit mode, please comment this in storm's configuration: `#nimbus.topology.validator: "resa.topology.ResaTopologyValidator"`, i.e., using Storm's default TopologyValidator.

In the meantime, we will re-organize the "TestTopology/simulated/" folder, move "ResaSimExpServWC.java", "ResaSimExpServWC2Path.java" and "ResaSimExpServWCLoop.java" to another folder, to solve this  ambiguation issue. 

Thanks
Tom

**Comment by Junyulu** [comment]
Hi Tom,

I really appreciate your prompt reply and assistance.I didn't notice the two modes of the Rest-drs.Your suggestions have perfectly solved the problems and eliminate my confusions.Thanks again for you help.

Best wishes
